#!/usr/bin/env bash
# End-to-end test harness: spawn a real Airflow, seed it, run the E2E suite.
#
# Usage:
#   scripts/e2e.sh [af2|af3]        # default: af2
#   E2E_KEEP=1 scripts/e2e.sh af2   # leave the container running afterwards
#   AIRFLOW_IMAGE=apache/airflow:2.10.5 scripts/e2e.sh af2   # override image
set -euo pipefail
cd "$(dirname "$0")/.."
REPO_ROOT="$PWD"

ENTRY="${1:-af2}"
case "$ENTRY" in
  af2)
    IMAGE_DEFAULT="apache/airflow:2.11.0"
    API=v1
    # The generated v1 client series ends at 2.10.0 and remains the client for
    # Airflow 2.11's stable API.
    CLIENT_PIN="apache-airflow-client==2.10.0"
    ;;
  af3)
    IMAGE_DEFAULT="apache/airflow:3.3.0"
    API=v2
    CLIENT_PIN="apache-airflow-client==3.3.0"
    ;;
  *)
    echo "usage: $0 [af2|af3]" >&2
    exit 2
    ;;
esac

COMPOSE="tests/e2e/docker/compose.${ENTRY}.yml"
export AIRFLOW_IMAGE="${AIRFLOW_IMAGE:-$IMAGE_DEFAULT}"
# Let Docker allocate a free loopback port. A unique Compose project keeps
# containers, networks, and volumes owned by this invocation, so concurrent
# local runs cannot join or tear down one another's environment. CI may provide
# its own run-unique name when a later step needs to inspect the same project.
export AIRFLOW_HOST_PORT=0
COMPOSE_PROJECT="${E2E_COMPOSE_PROJECT:-airflow-mcp-e2e-${ENTRY}-$$-${RANDOM}}"
TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/airflow-mcp-e2e-${ENTRY}.XXXXXX")"
DIST_DIR="$TMP_DIR/dist"
ARTIFACT_VENV="$TMP_DIR/artifact-venv"
ENV_OWNED=0
BASE_URL=""

compose() {
  docker compose --project-name "$COMPOSE_PROJECT" -f "$COMPOSE" "$@"
}

cleanup() {
  status=$?
  if [[ "$status" != "0" && "$ENV_OWNED" == "1" && "${E2E_DUMP_LOGS_ON_FAILURE:-0}" == "1" ]]; then
    echo "== [$ENTRY] Airflow logs after E2E failure ==" >&2
    compose logs --tail 200 >&2 || true
  fi
  if [[ "${E2E_KEEP:-0}" == "1" && "$ENV_OWNED" == "1" ]]; then
    echo "E2E_KEEP=1 — leaving project $COMPOSE_PROJECT running ($BASE_URL, admin/admin)"
    echo "inspect with: docker compose --project-name $COMPOSE_PROJECT -f $COMPOSE logs"
    echo "registry: $TMP_DIR/instances.yaml"
  else
    if [[ "$ENV_OWNED" == "1" ]]; then
      compose down -v || true
    fi
    rm -rf "$TMP_DIR"
  fi
  return "$status"
}
trap cleanup EXIT

echo "== [$ENTRY] building and installing wheel (client pin: $CLIENT_PIN) =="
uv build --wheel --out-dir "$DIST_DIR"
WHEEL="$(find "$DIST_DIR" -maxdepth 1 -type f -name '*.whl' -print -quit)"
if [[ -z "$WHEEL" ]]; then
  echo "wheel build did not produce an artifact in $DIST_DIR" >&2
  exit 1
fi
uv venv "$ARTIFACT_VENV"
uv pip install --python "$ARTIFACT_VENV/bin/python" \
  "$WHEEL" "$CLIENT_PIN" "pytest==8.4.2" "pytest-asyncio==1.2.0"
for executable in airflow-mcp apache-airflow-mcp-server; do
  if [[ ! -x "$ARTIFACT_VENV/bin/$executable" ]]; then
    echo "installed console script not found: $ARTIFACT_VENV/bin/$executable" >&2
    exit 1
  fi
done
# Exercise the package-name alias used by official MCP Registry consumers.
export E2E_INSTALLED_AIRFLOW_MCP="$ARTIFACT_VENV/bin/apache-airflow-mcp-server"

echo "== [$ENTRY] starting $AIRFLOW_IMAGE (project: $COMPOSE_PROJECT) =="
ENV_OWNED=1
compose up -d --wait

PORT_BINDING="$(compose port airflow 8080)"
PORT="${PORT_BINDING##*:}"
if [[ ! "$PORT" =~ ^[0-9]+$ ]]; then
  echo "could not determine Airflow host port from: $PORT_BINDING" >&2
  exit 1
fi
BASE_URL="http://localhost:${PORT}"
echo "== [$ENTRY] Airflow ready on $BASE_URL =="

echo "== [$ENTRY] seeding =="
uv run python tests/e2e/seed.py --base-url "$BASE_URL" --api-version "$API"

cat > "$TMP_DIR/instances.yaml" <<EOF
# Generated by scripts/e2e.sh — test-only credentials for the local container.
e2e-local:
  host: ${BASE_URL}
  api_version: ${API}
  auth:
    type: basic
    username: admin
    password: admin
e2e-alias:
  host: http://127.0.0.1:${PORT}
  api_version: ${API}
  auth:
    type: basic
    username: admin
    password: admin
EOF

if [[ "$ENTRY" == "af3" ]]; then
  # Fetch independently of the implementation under test. This entry proves
  # that the generated v2 client can use a caller-supplied bearer token rather
  # than silently falling back to the basic->JWT exchange path.
  BEARER_TOKEN="$({
    curl --fail --silent --show-error \
      --request POST \
      --header 'Content-Type: application/json' \
      --data '{"username":"admin","password":"admin"}' \
      "$BASE_URL/auth/token"
  } | "$ARTIFACT_VENV/bin/python" -c \
    'import json, sys; print(json.load(sys.stdin)["access_token"])')"
  if [[ -z "$BEARER_TOKEN" ]]; then
    echo "Airflow 3 token endpoint returned an empty access token" >&2
    exit 1
  fi
  cat >> "$TMP_DIR/instances.yaml" <<EOF
e2e-bearer:
  host: ${BASE_URL}
  api_version: v2
  auth:
    type: bearer
    token: ${BEARER_TOKEN}
EOF
  export E2E_BEARER_INSTANCE="e2e-bearer"
  # Keep this short enough for the E2E refresh test to cross the deadline while
  # still making two genuine calls to the live /auth/token endpoint.
  export AIRFLOW_MCP_TOKEN_REFRESH_SECONDS=1
fi

export AIRFLOW_MCP_INSTANCES_FILE="$TMP_DIR/instances.yaml"
export AIRFLOW_MCP_DEFAULT_INSTANCE="e2e-local"
export E2E_AIRFLOW_BASE_URL="$BASE_URL"
export E2E_AIRFLOW_API_VERSION="$API"
export E2E_ALLOW_WRITES=1
export E2E_HARNESS_NONCE="$COMPOSE_PROJECT"

echo "== [$ENTRY] running E2E suite (client pin: $CLIENT_PIN) =="
(
  cd "$TMP_DIR"
  unset PYTHONPATH VIRTUAL_ENV
  "$ARTIFACT_VENV/bin/pytest" "$REPO_ROOT/tests/e2e" \
    -c /dev/null --rootdir "$TMP_DIR" \
    -o asyncio_mode=strict -o "markers=e2e: live end-to-end tests" \
    -v "${@:2}"
)
